# google smtp server
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hyunchoi@hist.co.kr
    password: sgglbprtchvgmuqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 관리자 이메일
system.info.email: choihyunji1103@gmail.com

# jwt token
props.jwt.expire-access: 86400000   # 1일
props.jwt.expire-refresh: 172800000 # 2일
